spring:
  main:
    lazy-initialization: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: ${PORT:10000}

logging:
  level:
    com.overwatch.patchtracker: INFO
    org.hibernate: WARN